# Part of Speech(POS) Tagging

In [1]:
import spacy
import pandas as pd

In [2]:
nlp = spacy.load('en_core_web_sm')
#using the english core web small model from spacy library for 
#if running first time use the command: python -m spacy download en_core_web_sm

In [3]:
emma = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"
#print(emma)

In [19]:
spacy_doc = nlp(emma)
#generating spacy_doc from emma, this will have the tokens ans the associated POS tags

In [21]:
#using pandas transform the doc into DataFrame containing tokens and POS tags
pos_df = pd.DataFrame(columns=['token', 'pos_tag'])
pos_df

Empty DataFrame
Columns: [token, pos_tag]
Index: []

In [22]:
for token in spacy_doc:
    pos_df = pd.concat([pos_df, pd.DataFrame.from_records([{'token': token.text, 'pos_tag': token.pos_}])], ignore_index=True)

In [24]:
#pos_df.head(10)

In [28]:
#token frequency counts
pos_df_counts = pos_df.groupby(['token','pos_tag']).size().reset_index(name='counts').sort_values(by='counts',ascending=False)
#pos_df_counts.head(10)

In [29]:
pos_df_poscounts = pos_df_counts.groupby(['pos_tag'])['token'].count().sort_values(ascending=False)

In [30]:
pos_df_poscounts

pos_tag
NOUN     35
VERB     19
ADJ      18
ADV      18
PRON      9
ADP       8
PROPN     6
DET       5
AUX       4
CCONJ     3
NUM       3
SCONJ     3
PART      1
Name: token, dtype: int64

In [34]:
nouns = pos_df_counts[pos_df_counts.pos_tag == 'NOUN'][0:10]
nouns

           token pos_tag  counts
46        friend    NOUN       3
48     governess    NOUN       3
28     daughters    NOUN       2
82        mother    NOUN       2
103      sisters    NOUN       2
35          emma    NOUN       2
130        years    NOUN       2
100       shadow    NOUN       1
97     restraint    NOUN       1
96   remembrance    NOUN       1

In [36]:
verbs = pos_df_counts[pos_df_counts.pos_tag =='ADJ'][0:10]
verbs

            token pos_tag  counts
70         little     ADJ       2
102         short     ADJ       1
98           rich     ADJ       1
91            own     ADJ       1
86        nominal     ADJ       1
131      youngest     ADJ       1
2    affectionate     ADJ       1
79           more     ADJ       1
50       handsome     ADJ       1
44           fond     ADJ       1